export interface IDatabaseInfo {
  database_id: number;
  name: string;
  create_date: Date;
  compatibility_level?: number;
  collation_name?: string;
  user_access_desc?: string;
  state_desc?: string;
  recovery_model_desc?: string;
  containment_desc?: string;
}


export interface IDatabaseDetailsInfo {
  name: string;
  database_id: number;
  source_database_id: number | null;
  owner_sid: { type: string; data: number[] };
  create_date: string;
  compatibility_level: number;
  collation_name: string;
  user_access: number;
  user_access_desc: string;
  is_read_only: boolean;
  is_auto_close_on: boolean;
  is_auto_shrink_on: boolean;
  state: number;
  state_desc: string;
  is_in_standby: boolean;
  is_cleanly_shutdown: boolean;
  is_supplemental_logging_enabled: boolean;
  snapshot_isolation_state: number;
  snapshot_isolation_state_desc: string;
  is_read_committed_snapshot_on: boolean;
  recovery_model: number;
  recovery_model_desc: string;
  page_verify_option: number;
  page_verify_option_desc: string;
  is_auto_create_stats_on: boolean;
  is_auto_create_stats_incremental_on: boolean;
  is_auto_update_stats_on: boolean;
  is_auto_update_stats_async_on: boolean;
  is_ansi_null_default_on: boolean;
  is_ansi_nulls_on: boolean;
  is_ansi_padding_on: boolean;
  is_ansi_warnings_on: boolean;
  is_arithabort_on: boolean;
  is_concat_null_yields_null_on: boolean;
  is_numeric_roundabort_on: boolean;
  is_quoted_identifier_on: boolean;
  is_recursive_triggers_on: boolean;
  is_cursor_close_on_commit_on: boolean;
  is_local_cursor_default: boolean;
  is_fulltext_enabled: boolean;
  is_trustworthy_on: boolean;
  is_db_chaining_on: boolean;
  is_parameterization_forced: boolean;
  is_master_key_encrypted_by_server: boolean;
  is_query_store_on: boolean;
  is_published: boolean;
  is_subscribed: boolean;
  is_merge_published: boolean;
  is_distributor: boolean;
  is_sync_with_backup: boolean;
  service_broker_guid: string;
  is_broker_enabled: boolean;
  log_reuse_wait: number;
  log_reuse_wait_desc: string;
  is_date_correlation_on: boolean;
  is_cdc_enabled: boolean;
  is_encrypted: boolean;
  is_honor_broker_priority_on: boolean;
  replica_id: string | null;
  group_database_id: string | null;
  resource_pool_id: number | null;
  default_language_lcid: number | null;
  default_language_name: string | null;
  default_fulltext_language_lcid: number | null;
  default_fulltext_language_name: string | null;
  is_nested_triggers_on: boolean | null;
  is_transform_noise_words_on: boolean | null;
  two_digit_year_cutoff: number | null;
  containment: number;
  containment_desc: string;
  target_recovery_time_in_seconds: number;
  delayed_durability: number;
  delayed_durability_desc: string;
  is_memory_optimized_elevate_to_snapshot_on: boolean;
  is_federation_member: boolean;
  is_remote_data_archive_enabled: boolean;
  is_mixed_page_allocation_on: boolean;
  is_temporal_history_retention_enabled: boolean;
  catalog_collation_type: number;
  catalog_collation_type_desc: string;
  physical_database_name: string;
  is_result_set_caching_on: boolean;
  is_accelerated_database_recovery_on: boolean;
  is_tempdb_spill_to_remote_store: boolean;
  is_stale_page_detection_on: boolean;
  is_memory_optimized_enabled: boolean;
}